#!/usr/bin/env python3
"""
Two-level conformal inference for LLM-generated reason sets.

This module implements two-level conformal inference to:
1. Create prediction sets guaranteed to contain the true top reason
2. Provide upper bounds on the true score of the best reason

Theory (Theorem: Two-Level Conformal Inference):
Let Â(X) be the set of reasons generated by an LLM for observation X.
For reason a and observation X:
  - Ŷ(a, X) = LLM-assigned score
  - Y*(a, X) = true (human) score
  - a*(X) = argmax_{a} Y*(a, X) = true best reason

Define two residuals:
  Δ₁(X) = max_{a∈Â(X)} Ŷ(a,X) - Ŷ(a*(X), X)
  Δ₂(X) = Y*(a*(X), X) - Ŷ(a*(X), X)

The conformalized reason set is:
  Â_CI(X) = {a : a∈Â(X), Ŷ(a,X) ≥ max Ŷ - Q_{1-α}(Δ₁)}

The upper bound on the true best score is:
  max_{a∈Â_CI(X)} Ŷ(a,X) + Q_{1-α}(Δ₂ for observations in selected set)

With probability ≥ (1-α)²:
  (i) The prediction set contains the true best reason
  (ii) The true score of the best reason is upper bounded
"""

import logging
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd


class StandardConformalInference:
    """Standard conformal inference for individual reason score bounds.

    This baseline treats each (observation, reason) pair as an independent
    exchangeable unit and provides upper bounds on the true score for each reason.

    Residual: Δ(a, X) = Y*(a, X) - Ŷ(a, X)
    Upper bound: Ŷ(a, X) + Q_{1-α}(Δ)

    This provides 1-α coverage that the true score ≤ upper bound for each reason,
    ignoring the hierarchical structure of reason generation.
    """

    def __init__(self):
        """Initialize the standard conformal inference model."""
        self.delta_values: Optional[np.ndarray] = None
        self.n_calibration_points: int = 0
        self.is_fitted: bool = False
        self.logger = logging.getLogger(__name__)

    def fit(self, annotations: pd.DataFrame) -> Dict:
        """Fit the standard conformal inference model.

        Computes residuals Δ(a, X) = Y*(a, X) - Ŷ(a, X) for each reason.

        Args:
            annotations: DataFrame with columns:
                - encounter_id: observation identifier
                - reason_id: reason identifier within observation
                - LLM_confidence: Ŷ(a, X) - LLM assigned score
                - annotation: Y*(a, X) - human/true score

        Returns:
            Dict with fit statistics
        """
        required_cols = ["encounter_id", "reason_id", "LLM_confidence", "annotation"]
        for col in required_cols:
            assert col in annotations.columns, f"Missing required column: {col}"

        # Filter to valid rows
        df = annotations[
            annotations["LLM_confidence"].notna() &
            annotations["annotation"].notna()
        ].copy()

        assert len(df) > 0, "No valid annotations with both LLM_confidence and annotation"

        # If multiple reviewers annotated the same reason, aggregate by taking mean
        df_agg = (
            df.groupby(["encounter_id", "reason_id"])
            .agg({
                "LLM_confidence": "first",  # Same for all reviewers
                "annotation": "mean",  # Average across reviewers
            })
            .reset_index()
        )

        # Compute Δ = Y* - Ŷ for each reason (can be negative if LLM overestimates)
        df_agg["delta"] = df_agg["annotation"] - df_agg["LLM_confidence"]

        self.delta_values = df_agg["delta"].values
        self.n_calibration_points = len(self.delta_values)
        self.is_fitted = True

        return {
            "n_calibration_points": self.n_calibration_points,
            "n_observations": df_agg["encounter_id"].nunique(),
            "delta_values": self.delta_values,
            "delta_mean": float(np.mean(self.delta_values)),
            "delta_std": float(np.std(self.delta_values)),
            "delta_median": float(np.median(self.delta_values)),
            "delta_min": float(np.min(self.delta_values)),
            "delta_max": float(np.max(self.delta_values)),
        }

    def _compute_quantile(self, values: np.ndarray, alpha: float) -> float:
        """Compute finite-sample corrected quantile.

        Uses ceil((n+1)(1-α))-th order statistic for coverage guarantee.
        """
        n = len(values)
        k = int(np.ceil((n + 1) * (1 - alpha)))

        if k > n:
            return float("inf")

        sorted_values = np.sort(values)
        return float(sorted_values[k - 1])

    def get_quantile(self, alpha: float) -> float:
        """Get Q_{1-α}(Δ) for upper bound construction.

        Args:
            alpha: Miscoverage rate (e.g., 0.1 for 90% coverage)

        Returns:
            The (1-α) quantile of residuals
        """
        assert self.is_fitted, "Must call fit() before get_quantile()"
        assert 0 < alpha < 1, f"alpha must be in (0, 1), got {alpha}"
        return self._compute_quantile(self.delta_values, alpha)

    def get_upper_bounds(
        self,
        reasons: pd.DataFrame,
        alpha: float = 0.1,
    ) -> Tuple[pd.DataFrame, Dict]:
        """Get upper bounds on true scores for reasons.

        Upper bound: Ŷ(a, X) + Q_{1-α}(Δ)

        Args:
            reasons: DataFrame with LLM_confidence column
            alpha: Miscoverage rate

        Returns:
            Tuple of:
                - DataFrame with score_upper_bound column added
                - Dict with metadata
        """
        assert self.is_fitted, "Must call fit() before get_upper_bounds()"
        assert "LLM_confidence" in reasons.columns, "Missing LLM_confidence column"

        q = self.get_quantile(alpha)

        result = reasons.copy()
        result["score_upper_bound"] = result["LLM_confidence"] + q

        metadata = {
            "alpha": alpha,
            "coverage_target": 1 - alpha,
            "quantile": q,
            "mean_upper_bound": float(result["score_upper_bound"].mean()),
            "median_upper_bound": float(result["score_upper_bound"].median()),
        }

        return result, metadata

    def evaluate_coverage(
        self,
        test_annotations: pd.DataFrame,
        alpha: float = 0.1,
    ) -> Dict:
        """Evaluate empirical coverage on test data.

        Checks if Y*(a, X) ≤ Ŷ(a, X) + q for each reason.

        Args:
            test_annotations: DataFrame with same format as fit()
            alpha: Miscoverage rate

        Returns:
            Dict with coverage statistics
        """
        assert self.is_fitted, "Must call fit() before evaluate_coverage()"

        required_cols = ["encounter_id", "reason_id", "LLM_confidence", "annotation"]
        for col in required_cols:
            assert col in test_annotations.columns, f"Missing required column: {col}"

        df = test_annotations[
            test_annotations["LLM_confidence"].notna() &
            test_annotations["annotation"].notna()
        ].copy()

        # Aggregate if needed
        df_agg = (
            df.groupby(["encounter_id", "reason_id"])
            .agg({
                "LLM_confidence": "first",
                "annotation": "mean",
            })
            .reset_index()
        )

        q = self.get_quantile(alpha)
        df_agg["upper_bound"] = df_agg["LLM_confidence"] + q
        df_agg["is_covered"] = df_agg["annotation"] <= df_agg["upper_bound"]

        n_covered = df_agg["is_covered"].sum()
        n_total = len(df_agg)

        # Compute bound widths (how much we add to LLM score)
        # Width is just q for all reasons in standard conformal
        df_agg["bound_width"] = q

        return {
            "alpha": alpha,
            "coverage_target": 1 - alpha,
            "coverage_empirical": n_covered / n_total,
            "n_covered": n_covered,
            "n_total": n_total,
            "quantile": q,
            "mean_upper_bound": float(df_agg["upper_bound"].mean()),
            "median_upper_bound": float(df_agg["upper_bound"].median()),
            "min_upper_bound": float(df_agg["upper_bound"].min()),
            "max_upper_bound": float(df_agg["upper_bound"].max()),
            "details": df_agg,
        }


class ConformalInference:
    """Two-level conformal inference for LLM reason scoring.

    This class computes calibration residuals (Δ₁, Δ₂) from annotated data and
    provides prediction sets with coverage guarantees and score upper bounds.
    """

    def __init__(self):
        """Initialize the conformal inference model."""
        self.delta1_values: Optional[np.ndarray] = None
        self.delta2_values: Optional[np.ndarray] = None
        self.delta2_selected: Optional[np.ndarray] = None
        self.selected_indices: Optional[np.ndarray] = None
        self.n_observations: int = 0
        self.is_fitted: bool = False
        self.logger = logging.getLogger(__name__)

    def fit(self, annotations: pd.DataFrame, alpha: float = 0.1) -> Dict:
        """Fit the two-level conformal inference model.

        For each observation (encounter_id), computes:
        Δ₁(X) = max_{a} Ŷ(a,X) - Ŷ(a*(X), X)
        Δ₂(X) = Y*(a*(X), X) - Ŷ(a*(X), X)

        Then identifies the selected set I = {i : Δ₁(Xᵢ) ≤ Q_{1-α}(Δ₁)}
        and computes q₂ from Δ₂ values of observations in I.

        Args:
            annotations: DataFrame with columns:
                - encounter_id: observation identifier
                - reason_id: reason identifier within observation
                - LLM_confidence: Ŷ(a, X) - LLM assigned score (0-100)
                - annotation: Y*(a, X) - human/true score (1-5)
            alpha: Miscoverage rate (e.g., 0.1 for 90% coverage per level)

        Returns:
            Dict with fit statistics including deltas and summary stats
        """
        required_cols = ["encounter_id", "reason_id", "LLM_confidence", "annotation"]
        for col in required_cols:
            assert col in annotations.columns, f"Missing required column: {col}"

        # Filter to valid rows
        df = annotations[
            annotations["LLM_confidence"].notna() &
            annotations["annotation"].notna()
        ].copy()

        assert len(df) > 0, "No valid annotations with both LLM_confidence and annotation"

        # If multiple reviewers annotated the same reason, aggregate by taking mean
        df_agg = (
            df.groupby(["encounter_id", "reason_id"])
            .agg({
                "LLM_confidence": "first",  # Same for all reviewers
                "annotation": "mean",  # Average across reviewers
            })
            .reset_index()
        )

        # Compute Δ₁ and Δ₂ for each encounter
        delta1_list = []
        delta2_list = []
        encounter_stats = []

        for encounter_id, group in df_agg.groupby("encounter_id"):
            n_reasons = len(group)

            # Skip encounters with only one reason (Δ₁ would be 0 trivially)
            if n_reasons < 2:
                self.logger.debug(
                    f"Skipping encounter {encounter_id}: only {n_reasons} reason(s)"
                )
                continue

            # max_{a} Ŷ(a, X) - maximum LLM confidence
            max_llm_score = group["LLM_confidence"].max()

            # a*(X) = argmax_{a} Y*(a, X) - reason with highest human annotation
            # In case of ties, take the one with highest LLM score (conservative for Δ₁)
            max_human_score = group["annotation"].max()
            best_human_reasons = group[group["annotation"] == max_human_score]

            # Get LLM score for the true best reason
            # If tied, use the one with highest LLM score (gives smallest Δ₁)
            llm_score_of_true_best = best_human_reasons["LLM_confidence"].max()

            # Compute Δ₁ = max Ŷ - Ŷ(a*)
            delta1 = max_llm_score - llm_score_of_true_best
            assert delta1 >= 0, f"Δ₁ should be non-negative, got {delta1}"

            # Compute Δ₂ = Y*(a*) - Ŷ(a*)
            # Note: This can be negative if LLM overestimates the true score
            delta2 = max_human_score - llm_score_of_true_best

            delta1_list.append(delta1)
            delta2_list.append(delta2)
            encounter_stats.append({
                "encounter_id": encounter_id,
                "n_reasons": n_reasons,
                "max_llm_score": max_llm_score,
                "max_human_score": max_human_score,
                "llm_score_of_true_best": llm_score_of_true_best,
                "delta1": delta1,
                "delta2": delta2,
            })

        assert len(delta1_list) > 0, "No encounters with multiple reasons found"

        self.delta1_values = np.array(delta1_list)
        self.delta2_values = np.array(delta2_list)
        self.n_observations = len(delta1_list)

        # Compute q₁ and identify selected set I
        q1 = self._compute_quantile(self.delta1_values, alpha)
        self.selected_indices = np.where(self.delta1_values <= q1)[0]
        self.delta2_selected = self.delta2_values[self.selected_indices]

        self.is_fitted = True
        self._alpha = alpha  # Store alpha used during fitting

        return {
            "n_observations": self.n_observations,
            "alpha": alpha,
            # Δ₁ statistics
            "delta1_values": self.delta1_values,
            "delta1_mean": float(np.mean(self.delta1_values)),
            "delta1_std": float(np.std(self.delta1_values)),
            "delta1_median": float(np.median(self.delta1_values)),
            "delta1_min": float(np.min(self.delta1_values)),
            "delta1_max": float(np.max(self.delta1_values)),
            "q1": float(q1),
            # Selected set statistics
            "n_selected": len(self.selected_indices),
            "selection_rate": len(self.selected_indices) / self.n_observations,
            # Δ₂ statistics (from selected set)
            "delta2_selected": self.delta2_selected,
            "delta2_mean": float(np.mean(self.delta2_selected)) if len(self.delta2_selected) > 0 else None,
            "delta2_std": float(np.std(self.delta2_selected)) if len(self.delta2_selected) > 0 else None,
            "delta2_median": float(np.median(self.delta2_selected)) if len(self.delta2_selected) > 0 else None,
            "delta2_min": float(np.min(self.delta2_selected)) if len(self.delta2_selected) > 0 else None,
            "delta2_max": float(np.max(self.delta2_selected)) if len(self.delta2_selected) > 0 else None,
            "encounter_stats": pd.DataFrame(encounter_stats),
        }

    def _compute_quantile(self, values: np.ndarray, alpha: float) -> float:
        """Compute finite-sample corrected quantile.

        Uses ceil((n+1)(1-α))-th order statistic for coverage guarantee.

        Args:
            values: Array of residual values
            alpha: Miscoverage rate

        Returns:
            The (1-α) quantile with finite-sample correction
        """
        n = len(values)
        k = int(np.ceil((n + 1) * (1 - alpha)))

        if k > n:
            return float("inf")

        sorted_values = np.sort(values)
        return float(sorted_values[k - 1])

    def get_quantile_q1(self, alpha: float) -> float:
        """Get q₁ = Q_{1-α}(Δ₁) for prediction set construction.

        Args:
            alpha: Miscoverage rate (e.g., 0.1 for 90% coverage)

        Returns:
            The (1-α) quantile of Δ₁ values
        """
        assert self.is_fitted, "Must call fit() before get_quantile_q1()"
        assert 0 < alpha < 1, f"alpha must be in (0, 1), got {alpha}"
        return self._compute_quantile(self.delta1_values, alpha)

    def get_quantile_q2(self, alpha: float) -> float:
        """Get q₂ = Q_{1-α}(Δ₂) for score upper bound.

        Uses only Δ₂ values from the selected set I (observations where Δ₁ ≤ q₁).

        Args:
            alpha: Miscoverage rate (e.g., 0.1 for 90% coverage)

        Returns:
            The (1-α) quantile of Δ₂ values from selected set
        """
        assert self.is_fitted, "Must call fit() before get_quantile_q2()"
        assert 0 < alpha < 1, f"alpha must be in (0, 1), got {alpha}"
        assert len(self.delta2_selected) > 0, "No observations in selected set"
        return self._compute_quantile(self.delta2_selected, alpha)

    def get_prediction_set(
        self,
        reasons: pd.DataFrame,
        alpha: float = 0.1,
    ) -> Tuple[pd.DataFrame, Dict]:
        """Get the conformal prediction set and score upper bound for a new observation.

        Returns:
        1. All reasons a where: Ŷ(a, X) ≥ max Ŷ - q₁
        2. Upper bound on true best score: max_{a∈Â_CI} Ŷ(a, X) + q₂

        With probability ≥ (1-α)²:
        - The prediction set contains the true best reason
        - The true score of the best reason ≤ upper bound

        Args:
            reasons: DataFrame with columns:
                - reason_id: reason identifier
                - reason_text: text of the reason (optional)
                - LLM_confidence: Ŷ(a, X) - LLM assigned score
            alpha: Miscoverage rate (e.g., 0.1 for 90% coverage per level)

        Returns:
            Tuple of:
                - DataFrame of reasons in the prediction set
                - Dict with metadata (thresholds, quantiles, upper bound, etc.)
        """
        assert self.is_fitted, "Must call fit() before get_prediction_set()"
        assert "LLM_confidence" in reasons.columns, "Missing LLM_confidence column"
        assert len(reasons) > 0, "Empty reasons DataFrame"

        # Get quantiles
        q1 = self.get_quantile_q1(alpha)
        q2 = self.get_quantile_q2(alpha)

        # Maximum LLM score for this observation
        max_llm_score = reasons["LLM_confidence"].max()

        # Threshold for inclusion in prediction set
        threshold = max_llm_score - q1

        # Select reasons meeting the threshold
        prediction_set = reasons[reasons["LLM_confidence"] >= threshold].copy()

        # Upper bound on true best score
        max_llm_in_set = prediction_set["LLM_confidence"].max()
        score_upper_bound = max_llm_in_set + q2

        metadata = {
            "alpha": alpha,
            "joint_coverage_target": (1 - alpha) ** 2,
            # Level 1: Prediction set
            "q1": q1,
            "max_llm_score": float(max_llm_score),
            "threshold": float(threshold),
            "n_reasons_total": len(reasons),
            "n_reasons_in_set": len(prediction_set),
            "set_size_fraction": len(prediction_set) / len(reasons),
            # Level 2: Score upper bound
            "q2": q2,
            "max_llm_in_set": float(max_llm_in_set),
            "score_upper_bound": float(score_upper_bound),
        }

        return prediction_set, metadata

    def get_prediction_sets_batch(
        self,
        observations: pd.DataFrame,
        alpha: float = 0.1,
    ) -> Tuple[pd.DataFrame, Dict]:
        """Get conformal prediction sets and score bounds for multiple observations.

        Args:
            observations: DataFrame with columns:
                - encounter_id: observation identifier
                - reason_id: reason identifier
                - reason_text: text of the reason (optional)
                - LLM_confidence: Ŷ(a, X) - LLM assigned score
            alpha: Miscoverage rate

        Returns:
            Tuple of:
                - DataFrame with 'in_prediction_set' and 'score_upper_bound' columns
                - Dict with aggregate statistics
        """
        assert self.is_fitted, "Must call fit() before get_prediction_sets_batch()"
        assert "encounter_id" in observations.columns, "Missing encounter_id column"

        q1 = self.get_quantile_q1(alpha)
        q2 = self.get_quantile_q2(alpha)

        # Compute max LLM score per encounter
        max_scores = (
            observations.groupby("encounter_id")["LLM_confidence"]
            .max()
            .rename("max_llm_score")
        )

        # Merge back and compute threshold
        df = observations.merge(max_scores, on="encounter_id")
        df["threshold"] = df["max_llm_score"] - q1
        df["in_prediction_set"] = df["LLM_confidence"] >= df["threshold"]

        # Compute max LLM score within prediction set per encounter
        max_in_set = (
            df[df["in_prediction_set"]]
            .groupby("encounter_id")["LLM_confidence"]
            .max()
            .rename("max_llm_in_set")
        )
        df = df.merge(max_in_set, on="encounter_id", how="left")
        df["score_upper_bound"] = df["max_llm_in_set"] + q2

        # Compute aggregate stats
        set_sizes = df.groupby("encounter_id")["in_prediction_set"].sum()
        total_sizes = df.groupby("encounter_id").size()
        upper_bounds = df.groupby("encounter_id")["score_upper_bound"].first()

        metadata = {
            "alpha": alpha,
            "joint_coverage_target": (1 - alpha) ** 2,
            "q1": q1,
            "q2": q2,
            "n_observations": df["encounter_id"].nunique(),
            "mean_set_size": float(set_sizes.mean()),
            "median_set_size": float(set_sizes.median()),
            "mean_set_fraction": float((set_sizes / total_sizes).mean()),
            "mean_score_upper_bound": float(upper_bounds.mean()),
            "median_score_upper_bound": float(upper_bounds.median()),
        }

        # Clean up temporary columns
        result = df.drop(columns=["max_llm_score", "threshold", "max_llm_in_set"])

        return result, metadata

    def evaluate_coverage(
        self,
        test_annotations: pd.DataFrame,
        alpha: float = 0.1,
    ) -> Dict:
        """Evaluate empirical coverage on test data.

        Checks both levels of the guarantee:
        (i) Does the prediction set contain the true top reason?
        (ii) Is the true score of the best reason ≤ upper bound?

        Args:
            test_annotations: DataFrame with same format as fit()
            alpha: Miscoverage rate

        Returns:
            Dict with coverage statistics for both levels
        """
        assert self.is_fitted, "Must call fit() before evaluate_coverage()"

        required_cols = ["encounter_id", "reason_id", "LLM_confidence", "annotation"]
        for col in required_cols:
            assert col in test_annotations.columns, f"Missing required column: {col}"

        df = test_annotations[
            test_annotations["LLM_confidence"].notna() &
            test_annotations["annotation"].notna()
        ].copy()

        # Aggregate if needed
        df_agg = (
            df.groupby(["encounter_id", "reason_id"])
            .agg({
                "LLM_confidence": "first",
                "annotation": "mean",
            })
            .reset_index()
        )

        q1 = self.get_quantile_q1(alpha)
        q2 = self.get_quantile_q2(alpha)

        level1_covered = 0
        level2_covered = 0
        joint_covered = 0
        total = 0
        coverage_details = []

        for encounter_id, group in df_agg.groupby("encounter_id"):
            if len(group) < 2:
                continue

            total += 1

            # Find true top reason(s) and true best score
            max_human = group["annotation"].max()
            true_top_mask = group["annotation"] == max_human

            # Compute prediction set
            max_llm = group["LLM_confidence"].max()
            threshold = max_llm - q1
            pred_set_mask = group["LLM_confidence"] >= threshold

            # Level 1: Check if any true top reason is in prediction set
            is_level1_covered = (true_top_mask & pred_set_mask).any()
            if is_level1_covered:
                level1_covered += 1

            # Level 2: Check if true best score ≤ upper bound
            max_llm_in_set = group.loc[pred_set_mask, "LLM_confidence"].max()
            score_upper_bound = max_llm_in_set + q2
            is_level2_covered = max_human <= score_upper_bound
            if is_level2_covered:
                level2_covered += 1

            # Joint coverage
            is_joint_covered = is_level1_covered and is_level2_covered
            if is_joint_covered:
                joint_covered += 1

            coverage_details.append({
                "encounter_id": encounter_id,
                "n_reasons": len(group),
                "n_true_top": true_top_mask.sum(),
                "n_in_pred_set": pred_set_mask.sum(),
                "true_best_score": max_human,
                "max_llm_in_set": max_llm_in_set,
                "score_upper_bound": score_upper_bound,
                "is_level1_covered": is_level1_covered,
                "is_level2_covered": is_level2_covered,
                "is_joint_covered": is_joint_covered,
            })

        assert total > 0, "No valid test observations found"

        return {
            "alpha": alpha,
            # Level 1: Prediction set coverage
            "level1_target": 1 - alpha,
            "level1_empirical": level1_covered / total,
            "level1_n_covered": level1_covered,
            # Level 2: Score upper bound coverage
            "level2_target": 1 - alpha,
            "level2_empirical": level2_covered / total,
            "level2_n_covered": level2_covered,
            # Joint coverage
            "joint_target": (1 - alpha) ** 2,
            "joint_empirical": joint_covered / total,
            "joint_n_covered": joint_covered,
            # Total
            "n_total": total,
            "details": pd.DataFrame(coverage_details),
        }
